=== Letractively/jcatapult/jcatapult-deployment/trunk/src/xsd/deploy.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.jcatapult.org/schemas/deploy"
            xmlns="http://www.jcatapult.org/schemas/deploy"
            elementFormDefault="qualified">
  <xsd:complexType name="environment">
    <xsd:annotation>
      <xsd:documentation>
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="homeDir" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="workDir" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="fileDir" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="webDir" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="dbName" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="dbUsername" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="dbPassword" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="server">
    <xsd:annotation>
      <xsd:documentation>
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="environment" type="environment" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="platform" type="xsd:string" use="required"/>
    <xsd:attribute name="host" type="xsd:string" use="required"/>
    <xsd:attribute name="description" type="xsd:string" use="required"/>
    <xsd:attribute name="username" type="xsd:string" use="required"/>
    <xsd:attribute name="password" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:element name="deploy">
    <xsd:annotation>
      <xsd:documentation>
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="server" type="server" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Letractively/jcatapult/jcatapult-deployment/trunk/src/xml/examples/deploy.xml
<?xml version="1.0" encoding="UTF-8"?>
<deploy xmlns="http://www.jcatapult.org/schemas/deploy"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.jcatapult.org/schemas/deploy deploy.xsd"
        projectName="jcatapult-demo">
  <server platform="unix" host="demo.jcatapult.org" description="Demo Server" username="jcatapult-demo" password="jcatapult-demo">
    <environment type="staging">
      <homeDir>/home/jcatapult-demo</homeDir>
      <workDir>dev/work</workDir>
      <fileDir>dev/files</fileDir>
      <webDir>dev/apache-tomcat-5.5.26/webapps/ROOT</webDir>
      <dbName>jcatapult-demo</dbName>
      <dbUsername>jcatapult-demo</dbUsername>
      <dbPassword>jcatapult-demo</dbPassword>
    </environment>
  </server>
</deploy>
